# Witch keyboard devices to enable Keyd on
[ids]

# Enable on all keyboards/mice, etc. devices
*


# NEEDED?
# In order to change layout
# include layouts/se
# leftmeta+space = setlayout(se)


[global]

# Turn capslock light on when non-default layer (i.e. "main") is active
layer_indicator = 1

# How long to wait between emitted keys when executing a macro (in microseconds)
# macro_sequence_timeout =

# The maximum time between successive keys interpreted as part of a chord
chord_timeout = 100



# Layer
[main]

# Switch capslock and ESC
capslock = esc
esc = capslock

# Using overload() instead of layer() the latter doesn't have an option to preserve the original key's function when it's tapped
# WTF IS OVERLOADT DOING????
space = overloadt(navigation, space, 150)

space+tab = layer(macros)

# Could use something like "leftmeta = overload(leftmeta, leftmeta)" (taken from keyd.rvaiya(1)), define a leftmeta layer below
# and then use "space = toggle(swedish)" inside it, with the advantage being that you wouldn't have to depress both buttons simultaneously
# and instead could just press and hold leftmeta followed space. Downside is that it'd render other (window manager level) keybinds
# which function based off'f having leftmeta held down while pressing another key (e.g. leftmeta+w to close the current window) broken.
leftmeta+space = toggle(swedish)



# Layer
[navigation]

h = left
j = down
k = up
l = right

0 = home

# Composite layer (see man keyd.rvaiya(1))
[navigation+shift]
4 = end



# Layer
[macros]
# Note: sadly limited to 64 chars
# i = macro(ip space -c space -br space a enter)
e = macro(example)



# Layer
[swedish]

# Should normally use toggle() but cannot on the "main" layer
leftmeta+space = clear()

[ = å
' = ä
; = ö

# Composite layer (see man keyd.rvaiya(1))
[swedish+shift]
[ = Å
' = Ä
; = Ö

