# Custom version of Token dark (https://github.com/ThorstenRhau/token/)
background            #262624
foreground            #e8e4dc
selection_background  #3a3a37
selection_foreground  #e8e4dc
url_color             #e8622a
# cursor #e8e4dc
# cursor_text_color #262624

# Tabs
active_tab_background    #e8622a
active_tab_foreground    #262624
inactive_tab_background  #1d1d1c
inactive_tab_foreground  #938e87

# Windows
active_border_color    #e8622a
inactive_border_color  #2f2f2d

# normal
color0  #1d1d1c
color1  #e05252
color2  #52a842
color3  #e8b820
color4  #3880c8
color5  #a858e8
color6  #18c8be
color7  #d4cfc6

# bright
color8   #5a5955
color9   #e8622a
color10  #62c450
color11  #e09828
color12  #429ce0
color13  #c070f8
color14  #28d8d0
color15  #e8e4dc

# extended colors
color16  #e07828
color17  #e04040

background_opacity 1.0
